id = "templ"
name = "Templ"
version = "0.0.7"
schema_version = 1
authors = ["Mehmet Akif Duba <mail@makifdb.com>"]
description = "Templ language support for Zed"
repository = "https://github.com/makifdb/zed-templ"

[language_servers.templ]
name = "Templ Language Server"
language = "Templ"

[language_servers.templ.language_ids]
"Templ" = "templ"

[grammars.templ]
repository = "https://github.com/vrischmann/tree-sitter-templ"
commit = "0c114db6eb5f9a6a753340c4f12dd7d759aede8e"
